### ISSUE TITLE
Förderband erweiterung

### ISSUE THREAD

**Issue by JanZacher** [Achimobil/FS22_BaleConverterWithConveyerBelt#3]
Hi wer was möglich 2 m lange Förderband abschnitte zu machen das man das die zufür länger machen könnte

**Comment by Achimobil** [comment]
Mein Mod ist genau so wie er sein soll. Aber als Modder darf man die Skripte verwenden um eigene Mods daraus zu machen.
Hierzu ist aber Erfahrung im Modding notwendig, die ich aktuell nicht vermittel.
