### ISSUE TITLE
Strohbergungs Addon Kompatibilität

### ISSUE THREAD

**Issue by PanikPitty** [Achimobil/FS22_BaleConverterWithConveyerBelt#4]
Leider lassen sich mit dem Strohbergungs Addon gepresste Ballen nicht in HD Ballen konvertieren.
Vielleicht wäre es möglich, das anzupassen und ein Update zu bringen?

**Comment by Achimobil** [comment]
Das wird so nicht gehen, oder liefert das Pack auch HD ballen mit?
DAs skript ist so dass alle Filltypes angenommen werden im Eingang wo ein HD ballen für existiert.
Wenn es die HD ballen gibt, dann gern eine eine kurze beschreibung wie ich die HD ballen und die normalen ballen bekomme um mal zu testen

**Comment by PanikPitty** [comment]
Ich würde mal behaupten, dass das Addon keine eigenen HD Ballen mitliefert.
Dafür gibt es ja keine Presse, welche das Garn verwenden.
Es müssten also einfach nur als Eingangsprodukt die Ballen mit Garn in herkömmliche HD Ballen kovertiert werden.

**Comment by Achimobil** [comment]
Wenn es für den Filltype keine gibt werde ich bestimmt keine für die anlegen ;)

**Comment by Achimobil** [comment]
Gerade mal genau geschaut. Die haben keine eigenen Filltypes und ich hab mit deren Presse 2 Rundballen gemacht und in den Umpacker geworfen. Funktioniert wie du hier siehst. Also wo ist das Problem genau?
![fsScreen_2024_03_08_00_15_31](https://github.com/Achimobil/FS22_BaleConverterWithConveyerBelt/assets/65055783/4ef18f75-6bd0-4da7-98d7-cbcd81c5505f)

**Comment by PanikPitty** [comment]
Ich nutze dafür die Quaderballen und diese werden vom BaleConverter auch eingezogen, bleiben dann aber am Eingang des Umwandlers stehen und nicht weiter eingezogen.
Entweder liegt da ein Modkonflikt vor oder es ist etwas an der Karte.
Ich bin mit dem Problem auch nicht allein. Bin auch erst über ein YouTube Video darüber gestolpert.

**Comment by PanikPitty** [comment]
Hier mal ein Bild dazu und die Log.

![BaleConverter Talbach](https://github.com/Achimobil/FS22_BaleConverterWithConveyerBelt/assets/101251249/59527d63-f756-4705-a665-82557edfee25)

[log.txt](https://github.com/Achimobil/FS22_BaleConverterWithConveyerBelt/files/14532709/log.txt)

**Comment by PanikPitty** [comment]
![BaleConverter Talbach Rundballen](https://github.com/Achimobil/FS22_BaleConverterWithConveyerBelt/assets/101251249/ca1bf93b-6101-4082-9a98-77827dab14e5)

Das ganze auch nochmal mit den bereits auf der Map platzierten Ballen.

**Comment by Achimobil** [comment]
Hat die Map vielleicht keine Stroh HD Ballen?
Schau auch mal in die items.xml was der filltype ist bitte.
Es könnte aber auch an der Platzierung liegen dass dort der Ausgang blockiert ist durch irgendwelche Trigger Collisions.

**Comment by PanikPitty** [comment]
Danke für den Tipp mit dem Tortrigger! Scheinbar ist der Converter wirklich zu nah am Tor, denn außerhalb der Halle platziert, werden die Strohballen zu HD Ballen konvertiert.

**Comment by Achimobil** [comment]
cool, dann close ich das hier
